### ISSUE TITLE
CriticalPath CSS

### ISSUE THREAD

**Issue by trevski** [Taritsyn/BundleTransformer#51]
Have you considered adding in a CriticalPath css library? I have looked at this one https://github.com/addyosmani/critical I need it for ProteanCMS https://github.com/Eonic/ProteanCMS but rather than add it natively to my code it might be better architecture wise to add it to BundleTransformer that we are using.

Have you already had any thoughts on this? would you be open to working with me or having me work on a branch for you to later pull.

**Comment by Taritsyn** [comment]
Hello, Trevor!

Firstly, I do not create new Bundle Transformer's modules yet, because now I do not even have time to upgrade some of the old ones.

Secondly, as I understand it, the Critical-path CSS library extracts a CSS code from HTML pages. Processing of the content of web pages does not fit into architecture of the Microsoft ASP.NET Web Optimization Framework and Bundle Transformer, that are focused on working with style and script assets. I think that you need to create an HTTP module for this purpose.
