### ISSUE TITLE
[Q] ASP.NET Core support?

### ISSUE THREAD

**Issue by lonix1** [Taritsyn/BundleTransformer#81]
Was happy to see this library is being actively maintained after all these years. It works with `System.Web.Optimization` which is pre-Core.

But I couldn't determine from the docs, does this also support ASP.NET Core?

**Comment by Taritsyn** [comment]
Hello!

Bundle Transformer does not support ASP.NET Core, because it is an extension of the System.Web.Optimization library.

I recommend you to look at the following projects:
 1. [ASP.NET Core Web Optimizer](https://github.com/ligershark/WebOptimizer)
 1. [Smidge](https://github.com/Shazwazza/Smidge)
