### ISSUE TITLE
Support for `System.Text.Json` instead of `Newtonsoft.Json` on `BundleTransformer.Less`?

### ISSUE THREAD

**Issue by julealgon** [Taritsyn/BundleTransformer#84]
We'd like to eventually migrate all of our projects to use `System.Text.Json` exclusively. Is there any chance `BundleTransformer.Less` could also be made to work with `System.Text.Json` as the serializer dependency instead of relying on `Newtonsoft.Json`?

**Comment by Taritsyn** [comment]
Hello, Juliano!

> Is there any chance `BundleTransformer.Less` could also be made to work with `System.Text.Json` as the serializer dependency instead of relying on `Newtonsoft.Json`?

No. I will try to give a more detailed answer tomorrow.

**Comment by Taritsyn** [comment]
Hello, Juliano!

Bundle Transformer is first and foremost an modular extension for the [Microsoft ASP.NET Web Optimization Framework](https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization/). Microsoft ASP.NET Web Optimization Framework library has not been updated for 10 years. For this reason, Bundle Transformer is a legacy library that is now used by some very old CMS.

There are two reasons why I can't use `System.Text.Json` in the Bundle Transformer:
 1. Maintaining compatibility with .NET Framework 4.0.
 1. It is impossible to completely abandon `Newtonsoft.Json` because the Microsoft ASP.NET Web Optimization Framework library uses it (Microsoft.AspNet.Web.Optimization -> WebGrease -> Newtonsoft.Json).

Therefore, if you want to make your application free of unnecessary and very outdated dependencies, then I recommend you try to migrate to the [dotless.AspNetHandler](https://www.nuget.org/packages/dotless.AspNetHandler) library.

**Comment by julealgon** [comment]
Your explanation and suggestion are appreciated @Taritsyn . Closing this.
